#!/bin/sh

docker build --target dev -t task-master-php:dev ./docker
docker run -v ./:/app task-master-php:dev composer install

echo "Running Laravel Pint..."
docker run -v ./:/app task-master-php:dev php ./vendor/bin/pint --test --parallel

echo "Running Psalm..."
docker run -v ./:/app task-master-php:dev php ./vendor/bin/psalm --threads=4 --no-cache

echo "Running Tests..."
docker run -v ./:/app task-master-php:dev php artisan test --coverage --min=80
